bin/aoc with list and run commands

diff --git a/bin/aoc b/bin/aoc
--- a/bin/aoc
+++ b/bin/aoc
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 
-### Runs AoC solution for given day and language.
+### Advent of Code multi-language helper.
 ###
-### Usage:
-###    run <day> [<lang>]
+### Commands:
+###    list                List all solutions
+###    run <day> [<lang>]  Run solution for day and language
 ###
 ### Options:
 ###   <day>   advent day: e.g. 1, 3
@@ -25,23 +26,63 @@ then
   exit 0
 fi
 
-echo "🚀 Running AoC solution"
+# get command from first argument
+command="$1"
+if ! [[ $command =~ (list|run) ]];
+then
+  echo -e "\n🔴 Unknown command '$command'"
+  exit 1
+fi
 
-# get day from first argument and zero-pad
-arg1="$1"
-day=$(echo ${arg1//[!0-9]/} | xargs printf '%02d')
+# handle list command
+if [[ $command =~ list ]];
+then
+  echo -e "👻 AoC solutions\n"
+
+  echo -e "Elixir"
+  ls -1 "${rootDir}/elixir/lib" \
+    | grep day \
+    | sed -E 's/(day0?|.ex)//g' \
+    | awk '$0="  "$0'
+
+  echo -e "Haskell"
+  ls -1 "${rootDir}/haskell/app" \
+    | grep Day \
+    | sed -E 's/(Day0?|.hs)//g' \
+    | awk '$0="  "$0'
+
+  echo -e "Rust"
+  ls -1 "${rootDir}/rust/src/bin" \
+    | sed -E 's/(day0?|.rs)//g' \
+    | awk '$0="  "$0'
+
+  echo -e "TypeScript"
+  ls -1 "${rootDir}/typescript/src" \
+    | sed -E 's/(day0?|.ts)//g' \
+    | awk '$0="  "$0'
+
+  echo -e "\n✔ ok"
+  exit 0
+fi
+
+# handle run command
+echo -e "🚀 Running AoC solution"
+
+# get day from second argument and zero-pad
+arg2="$2"
+day=$(echo ${arg2//[!0-9]/} | xargs printf '%02d')
 
 # ensure day is two digits
 if ! [[ ${day} =~ ^[[:digit:]]{2}$ ]];
 then
-  echo "error: trouble parsing day number 🫣"
+  echo -e "\n🔴 Cannot parse day"
   exit 1
 fi
 
 # get lang
 langs='(elixir|haskell|rust|typescript)'
 
-if [ -z "$2" ];
+if [ -z "$3" ];
 then
   # second argument missing
   # try to get lang from current subfolder
@@ -53,13 +94,13 @@ then
   fi
 else
   # get lang rom second arg
-  lang="$2"
+  lang="$3"
 fi
 
 # ensure lang is valid
 if ! [[ ${lang} =~ ${langs} ]];
 then
-  echo "error: trouble parsing language 🫣"
+  echo -e "\n🔴 Cannot parse language"
   exit 1
 fi
 
@@ -70,9 +111,15 @@ case $lang in
     echo "-- Elixir ✔"
 
     langDir="${rootDir}/elixir"
+    filename="lib/day${day}.ex"
     cd $langDir
 
-    echo -e "-- Running lib/day${day}.ex\n"
+    if ! [[ -f "$langDir/${filename}" ]]; then
+      echo -e "\n🔴 Solution not found"
+      exit 1
+    fi
+
+    echo -e "-- Running ${filename}\n"
     MIX_QUIET=true mix run -e "Aoc.Day${day}.main()"
 
     ;;
@@ -83,6 +130,11 @@ case $lang in
     langDir="${rootDir}/haskell"
     inputFile="app/Day${day}"
     cd $langDir
+
+    if ! [[ -f "${inputFile}.hs" ]]; then
+      echo -e "\n🔴 Solution not found"
+      exit 1
+    fi
 
     echo -e "-- Running ${inputFile}.hs\n"
     stack runhaskell ${inputFile}
@@ -95,6 +147,11 @@ case $lang in
     langDir="${rootDir}/rust"
     inputFile="day${day}"
     cd $langDir
+
+    if ! [[ -f "src/bin/${inputFile}.rs" ]]; then
+      echo -e "\n🔴 Solution not found"
+      exit 1
+    fi
 
     echo -e "-- Running src/bin/${inputFile}.rs\n"
     cargo run --quiet --bin ${inputFile}
@@ -109,6 +166,11 @@ case $lang in
     outputFile="target/day${day}.js"
     cd $langDir
 
+    if ! [[ -f "${inputFile}" ]]; then
+      echo -e "\n🔴 Solution not found"
+      exit 1
+    fi
+
     echo -n "-- Compiling ${inputFile} => ${outputFile} "
     tsc ${inputFile} --outDir target
     echo "✔"
@@ -119,7 +181,7 @@ case $lang in
     ;;
 
   *)
-    echo "error: missing handler for language 🫣"
+    echo -e "\n🔴 Handler for language not found"
     exit 1
     ;;
 esac
